language: ruby
rvm:
  - 2.1.2

cache: bundler
script: bundle exec rake test

notifications:
  slack:
    secure: C5GyPZc5Cs496B0T11PYINZr4ktWPc/2PCGS1dFSg1tBTSMwUrjHyewWG19nygdd5jClGh8FEKWDLIUjfJBxK7HpOvQvwxtHBk/7i6m0TxGNtXygUFeULxQdINVMTLkD0sMFeXAnZE49FwrXQaDW6tZSzaHPLv4QtVpP1X5ms8M=

